// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace microsoft_hackathon_roi_calculator.MigrationService.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    partial class CalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("microsoft_hackathon_roi_calculator.Domain.Models.ProjectROI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedTraining")
                        .HasColumnType("int")
                        .HasColumnName("completed_training");

                    b.Property<int>("CompliantProcesses")
                        .HasColumnType("int")
                        .HasColumnName("compliant_processes");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("EmployeesUsingNewTool")
                        .HasColumnType("int")
                        .HasColumnName("employees_using_new_tool");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int")
                        .HasColumnName("number_of_employees");

                    b.Property<double>("ProjectBudget")
                        .HasColumnType("float")
                        .HasColumnName("project_budget");

                    b.Property<int>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("project_duration_months");

                    b.Property<int>("ProjectEvaluationPositiveResponses")
                        .HasColumnType("int")
                        .HasColumnName("project_evaluation_positive_responses");

                    b.Property<int>("ProjectEvaluationSumOfAllScores")
                        .HasColumnType("int")
                        .HasColumnName("project_evaluation_sum_of_all_scores");

                    b.Property<int>("ProjectEvaluationTotalResponses")
                        .HasColumnType("int")
                        .HasColumnName("project_evaluation_total_responses");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("project_name");

                    b.Property<double>("ROI")
                        .HasColumnType("float")
                        .HasColumnName("roi");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int>("TotalChangeImplementationTime")
                        .HasColumnType("int")
                        .HasColumnName("total_change_implementation_time");

                    b.Property<int>("TotalHoursWorkedWeekly")
                        .HasColumnType("int")
                        .HasColumnName("total_hours_worked_weekly");

                    b.Property<int>("TotalPlannedImplementationTime")
                        .HasColumnType("int")
                        .HasColumnName("total_planned_implementation_time");

                    b.Property<int>("TotalProcesses")
                        .HasColumnType("int")
                        .HasColumnName("total_processes");

                    b.HasKey("Id");

                    b.ToTable("roi", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
