# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = http://localhost:5508

POST {{host}}/api/roi
Content-Type: application/json
{
  "netBenefit": 5000.00,
  "costOfInvestment": 1000.00
}