# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = http://localhost:7173

GET {{host}}/api/CalculateROI
Content-Type: application/json
{
  "ProjectBudget": 20000,
  "NumberOfEmployees": 100,
  "ProjectDurationMonths": 5,
  "FailureRate": 0.2
}

